#!/bin/sh
[ -e /run/minecraft.stdin ] || { echo "Error: server is not running" >&2; exit 1; }
[ -n "$*" ] || { echo "Usage: minecraft <command>" >&2; exit 1; }
printf '%s\n' "$*" > /run/minecraft.stdin
